import { randomUUID } from 'node:crypto'
import sharp from 'sharp'
import { afterAll, beforeAll, describe, expect, it } from 'vitest'
import { getPayload, ValidationError, type Payload } from 'payload'

import { MEDIA_IMAGE_MAX_BYTES } from '@/collections/Media'
import config from '@/payload.config'

let payload: Payload
let publicMediaID: number | string
const createdMediaIDs: Array<number | string> = []

const buildMinimalPDF = (): Buffer => {
  const objects = [
    '1 0 obj\n<< /Type /Catalog /Pages 2 0 R >>\nendobj\n',
    '2 0 obj\n<< /Type /Pages /Kids [3 0 R] /Count 1 >>\nendobj\n',
    '3 0 obj\n<< /Type /Page /Parent 2 0 R /MediaBox [0 0 300 144] /Resources << /Font << /F1 5 0 R >> >> /Contents 4 0 R >>\nendobj\n',
    '4 0 obj\n<< /Length 48 >>\nstream\nBT /F1 12 Tf 36 72 Td (IVYBM demo PDF) Tj ET\nendstream\nendobj\n',
    '5 0 obj\n<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>\nendobj\n',
  ]
  let pdf = '%PDF-1.4\n'
  const offsets: number[] = []

  for (const object of objects) {
    offsets.push(Buffer.byteLength(pdf))
    pdf += object
  }

  const xrefOffset = Buffer.byteLength(pdf)
  pdf += `xref\n0 ${objects.length + 1}\n`
  pdf += '0000000000 65535 f \n'
  pdf += offsets.map((offset) => `${String(offset).padStart(10, '0')} 00000 n \n`).join('')
  pdf += `trailer\n<< /Size ${objects.length + 1} /Root 1 0 R >>\n`
  pdf += `startxref\n${xrefOffset}\n%%EOF\n`

  return Buffer.from(pdf)
}

describe.sequential('media policy integration', () => {
  beforeAll(async () => {
    if (!process.env.DATABASE_URL) {
      throw new Error('DATABASE_URL is required for media integration tests')
    }

    payload = await getPayload({
      config,
      disableOnInit: true,
      key: 'media-policy-integration-tests',
    })
  })

  afterAll(async () => {
    if (!payload) return

    for (const id of createdMediaIDs.reverse()) {
      await payload.delete({ collection: 'media', id, overrideAccess: true }).catch(() => undefined)
    }

    await payload.destroy()
  })

  it('requires a copyright source for every asset', async () => {
    const image = await sharp({
      create: { background: '#1c2f46', channels: 3, height: 600, width: 800 },
    })
      .png()
      .toBuffer()

    await expect(
      payload.create({
        collection: 'media',
        data: { alt: 'Missing source' } as never,
        file: {
          data: image,
          mimetype: 'image/png',
          name: `task5-missing-source-${randomUUID()}.png`,
          size: image.length,
        },
        overrideAccess: true,
      }),
    ).rejects.toBeInstanceOf(ValidationError)
  })

  it('generates responsive image sizes for an accepted image', async () => {
    const image = await sharp({
      create: { background: '#d9a441', channels: 3, height: 1200, width: 1800 },
    })
      .jpeg({ quality: 85 })
      .toBuffer()
    const media = await payload.create({
      collection: 'media',
      data: {
        alt: 'Owned aluminum facade placeholder',
        isPublic: true,
        source: 'IVYBM owned placeholder generated by the seed/test suite',
      },
      file: {
        data: image,
        mimetype: 'image/jpeg',
        name: `task5-responsive-${randomUUID()}.jpg`,
        size: image.length,
      },
      overrideAccess: true,
    })
    createdMediaIDs.push(media.id)
    publicMediaID = media.id

    expect(media.source).toContain('IVYBM owned')
    expect(media.sizes?.thumbnail?.width).toBe(400)
    expect(media.sizes?.thumbnail?.height).toBe(300)
    expect(media.sizes?.card?.width).toBe(768)
    expect(media.sizes?.card?.height).toBe(576)
    expect(media.sizes?.large?.width).toBe(1600)
  })

  it('keeps non-public assets out of ordinary anonymous reads', async () => {
    const image = await sharp({
      create: { background: '#222222', channels: 3, height: 600, width: 800 },
    })
      .jpeg()
      .toBuffer()
    const privateMedia = await payload.create({
      collection: 'media',
      context: { disableRevalidate: true },
      data: {
        alt: 'Private draft-only asset',
        isPublic: false,
        source: 'IVYBM generated test fixture',
      },
      file: {
        data: image,
        mimetype: 'image/jpeg',
        name: `task5-private-${randomUUID()}.jpg`,
        size: image.length,
      },
      overrideAccess: true,
    })
    createdMediaIDs.push(privateMedia.id)

    const result = await payload.find({
      collection: 'media',
      overrideAccess: false,
      where: {
        id: {
          in: [publicMediaID, privateMedia.id],
        },
      },
    })

    expect(result.docs.map((doc) => doc.id)).toEqual([publicMediaID])
  })

  it('accepts a valid PDF without generating image sizes', async () => {
    const pdf = buildMinimalPDF()
    const media = await payload.create({
      collection: 'media',
      data: {
        alt: 'Demo technical data PDF',
        isPublic: true,
        source: 'IVYBM generated test document',
      },
      file: {
        data: pdf,
        mimetype: 'application/pdf',
        name: `task5-document-${randomUUID()}.pdf`,
        size: pdf.length,
      },
      overrideAccess: true,
    })
    createdMediaIDs.push(media.id)

    expect(media.mimeType).toBe('application/pdf')
    expect(media.sizes?.thumbnail?.url).toBeFalsy()

    await expect(
      payload.create({
        collection: 'pages',
        data: {
          heroImage: media.id,
          slug: `pdf-hero-${randomUUID()}`,
          title: 'PDF hero should be rejected',
        },
        locale: 'en',
        overrideAccess: true,
      }),
    ).rejects.toBeInstanceOf(ValidationError)
  })

  it('rejects unsupported MIME types', async () => {
    const file = Buffer.from('<html>not an asset</html>')

    await expect(
      payload.create({
        collection: 'media',
        data: { alt: 'Invalid file', source: 'Test fixture' },
        file: {
          data: file,
          mimetype: 'text/html',
          name: `task5-invalid-${randomUUID()}.html`,
          size: file.length,
        },
        overrideAccess: true,
      }),
    ).rejects.toBeInstanceOf(ValidationError)
  })

  it('rejects image bytes that do not match the declared MIME type', async () => {
    const jpeg = await sharp({
      create: { background: '#1c2f46', channels: 3, height: 2, width: 2 },
    })
      .jpeg()
      .toBuffer()

    await expect(
      payload.create({
        collection: 'media',
        data: { alt: 'Mismatched image', source: 'Test fixture' },
        file: {
          data: jpeg,
          mimetype: 'image/png',
          name: `task5-mismatched-${randomUUID()}.png`,
          size: jpeg.length,
        },
        overrideAccess: true,
      }),
    ).rejects.toBeInstanceOf(ValidationError)
  })

  it('rejects oversized images through the Local API path', async () => {
    const oversized = Buffer.alloc(MEDIA_IMAGE_MAX_BYTES + 1)

    await expect(
      payload.create({
        collection: 'media',
        data: { alt: 'Oversized image', source: 'Test fixture' },
        file: {
          data: oversized,
          mimetype: 'image/png',
          name: `task5-oversized-${randomUUID()}.png`,
          size: oversized.length,
        },
        overrideAccess: true,
      }),
    ).rejects.toBeInstanceOf(ValidationError)
  })
})
