/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    'audit-logs': AuditLog;
    pages: Page;
    'product-categories': ProductCategory;
    products: Product;
    projects: Project;
    posts: Post;
    downloads: Download;
    'knowledge-documents': KnowledgeDocument;
    'knowledge-chunks': KnowledgeChunk;
    'prompt-templates': PromptTemplate;
    'lead-sources': LeadSource;
    leads: Lead;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    'audit-logs': AuditLogsSelect<false> | AuditLogsSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    'product-categories': ProductCategoriesSelect<false> | ProductCategoriesSelect<true>;
    products: ProductsSelect<false> | ProductsSelect<true>;
    projects: ProjectsSelect<false> | ProjectsSelect<true>;
    posts: PostsSelect<false> | PostsSelect<true>;
    downloads: DownloadsSelect<false> | DownloadsSelect<true>;
    'knowledge-documents': KnowledgeDocumentsSelect<false> | KnowledgeDocumentsSelect<true>;
    'knowledge-chunks': KnowledgeChunksSelect<false> | KnowledgeChunksSelect<true>;
    'prompt-templates': PromptTemplatesSelect<false> | PromptTemplatesSelect<true>;
    'lead-sources': LeadSourcesSelect<false> | LeadSourcesSelect<true>;
    leads: LeadsSelect<false> | LeadsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: ('false' | 'none' | 'null') | false | null | ('en' | 'ar') | ('en' | 'ar')[];
  globals: {
    'site-settings': SiteSetting;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
  };
  locale: 'en' | 'ar';
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  role: 'admin' | 'operator' | 'sales';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  /**
   * Copyright owner, license, or source reference for this asset.
   */
  source: string;
  /**
   * Allow anonymous website visitors to read and download this asset.
   */
  isPublic?: boolean | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    large?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "audit-logs".
 */
export interface AuditLog {
  id: number;
  action: 'create' | 'update' | 'delete' | 'login';
  resource: string;
  documentId: string;
  actor?: (number | null) | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  /**
   * Stable URL slug shared by all locales. Use Latin letters, numbers, and hyphens.
   */
  slug: string;
  summary?: string | null;
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  heroImage?: (number | null) | Media;
  seo?: {
    title?: string | null;
    description?: string | null;
    /**
     * Comma-separated keywords for search and content planning.
     */
    keywords?: string | null;
    /**
     * Optional canonical URL for this locale.
     */
    canonical?: string | null;
    ogImage?: (number | null) | Media;
    noIndex?: boolean | null;
  };
  /**
   * Internal notes only. Not rendered on the public website.
   */
  internalNotes?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "product-categories".
 */
export interface ProductCategory {
  id: number;
  title: string;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  /**
   * Stable URL slug shared by all locales. Use Latin letters, numbers, and hyphens.
   */
  slug: string;
  description?: string | null;
  sortOrder?: number | null;
  seo?: {
    title?: string | null;
    description?: string | null;
    /**
     * Comma-separated keywords for search and content planning.
     */
    keywords?: string | null;
    /**
     * Optional canonical URL for this locale.
     */
    canonical?: string | null;
    ogImage?: (number | null) | Media;
    noIndex?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products".
 */
export interface Product {
  id: number;
  title: string;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  /**
   * Stable URL slug shared by all locales. Use Latin letters, numbers, and hyphens.
   */
  slug: string;
  shortDescription?: string | null;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  category: number | ProductCategory;
  coverImage: number | Media;
  gallery?: (number | Media)[] | null;
  specifications?:
    | {
        label: string;
        value: string;
        id?: string | null;
      }[]
    | null;
  seo?: {
    title?: string | null;
    description?: string | null;
    /**
     * Comma-separated keywords for search and content planning.
     */
    keywords?: string | null;
    /**
     * Optional canonical URL for this locale.
     */
    canonical?: string | null;
    ogImage?: (number | null) | Media;
    noIndex?: boolean | null;
  };
  /**
   * Internal notes only. Not rendered on the public website.
   */
  internalNotes?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects".
 */
export interface Project {
  id: number;
  title: string;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  /**
   * Stable URL slug shared by all locales. Use Latin letters, numbers, and hyphens.
   */
  slug: string;
  summary?: string | null;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  location?: string | null;
  application?: string | null;
  coverImage: number | Media;
  gallery?: (number | Media)[] | null;
  seo?: {
    title?: string | null;
    description?: string | null;
    /**
     * Comma-separated keywords for search and content planning.
     */
    keywords?: string | null;
    /**
     * Optional canonical URL for this locale.
     */
    canonical?: string | null;
    ogImage?: (number | null) | Media;
    noIndex?: boolean | null;
  };
  /**
   * Internal notes only. Not rendered on the public website.
   */
  internalNotes?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: number;
  title: string;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  /**
   * Stable URL slug shared by all locales. Use Latin letters, numbers, and hyphens.
   */
  slug: string;
  excerpt?: string | null;
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  category: 'industry' | 'products' | 'projects' | 'company';
  featuredImage?: (number | null) | Media;
  publishedAt?: string | null;
  seo?: {
    title?: string | null;
    description?: string | null;
    /**
     * Comma-separated keywords for search and content planning.
     */
    keywords?: string | null;
    /**
     * Optional canonical URL for this locale.
     */
    canonical?: string | null;
    ogImage?: (number | null) | Media;
    noIndex?: boolean | null;
  };
  /**
   * Internal notes only. Not rendered on the public website.
   */
  internalNotes?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "downloads".
 */
export interface Download {
  id: number;
  title: string;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  /**
   * Stable URL slug shared by all locales. Use Latin letters, numbers, and hyphens.
   */
  slug: string;
  description?: string | null;
  type: 'catalog' | 'technical-data' | 'certificate' | 'other';
  file: number | Media;
  coverImage?: (number | null) | Media;
  isActive?: boolean | null;
  seo?: {
    title?: string | null;
    description?: string | null;
    /**
     * Comma-separated keywords for search and content planning.
     */
    keywords?: string | null;
    /**
     * Optional canonical URL for this locale.
     */
    canonical?: string | null;
    ogImage?: (number | null) | Media;
    noIndex?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "knowledge-documents".
 */
export interface KnowledgeDocument {
  id: number;
  sourceTitle: string;
  sourceType: 'faq' | 'product-manual' | 'technical-specification' | 'sales-script' | 'project-case' | 'other';
  sourceURL?: string | null;
  sourceFile?: (number | null) | Media;
  sourceVersion: string;
  locale: 'en' | 'ar';
  content: string;
  reviewStatus: 'draft' | 'reviewed' | 'archived';
  reviewedAt?: string | null;
  reviewedBy?: (number | null) | User;
  indexStatus: 'pending' | 'processing' | 'ready' | 'failed';
  indexedAt?: string | null;
  embeddingModel?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "knowledge-chunks".
 */
export interface KnowledgeChunk {
  id: number;
  document: number | KnowledgeDocument;
  stableId: string;
  index: number;
  locale: 'en' | 'ar';
  content: string;
  sourceTitle: string;
  sourceVersion: string;
  sourceURL?: string | null;
  embeddingModel?: string | null;
  embeddingDimensions?: number | null;
  embeddedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "prompt-templates".
 */
export interface PromptTemplate {
  id: number;
  key: string;
  purpose: 'customer-chat' | 'conversation-summary' | 'translation' | 'content-generation';
  locale: 'all' | 'en' | 'ar';
  version: number;
  template: string;
  variables?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  status: 'draft' | 'active' | 'archived';
  model?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "lead-sources".
 */
export interface LeadSource {
  id: number;
  name: string;
  /**
   * Stable integration key. Create a new source instead of renaming this value.
   */
  key: string;
  channel: 'website' | 'ai-chat' | 'social' | 'manual';
  isActive: boolean;
  description?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "leads".
 */
export interface Lead {
  id: number;
  requestId: string;
  idempotencyKey: string;
  source: number | LeadSource;
  locale: 'en' | 'ar';
  status: 'new' | 'contacted' | 'qualified' | 'disqualified';
  intentLevel: 'unscored' | 'a' | 'b' | 'c';
  assignedTo?: (number | null) | User;
  name: string;
  company?: string | null;
  country: string;
  email: string;
  phone?: string | null;
  interest?: string | null;
  message: string;
  sourceURL?: string | null;
  utm?: {
    source?: string | null;
    medium?: string | null;
    campaign?: string | null;
    term?: string | null;
    content?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'audit-logs';
        value: number | AuditLog;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'product-categories';
        value: number | ProductCategory;
      } | null)
    | ({
        relationTo: 'products';
        value: number | Product;
      } | null)
    | ({
        relationTo: 'projects';
        value: number | Project;
      } | null)
    | ({
        relationTo: 'posts';
        value: number | Post;
      } | null)
    | ({
        relationTo: 'downloads';
        value: number | Download;
      } | null)
    | ({
        relationTo: 'knowledge-documents';
        value: number | KnowledgeDocument;
      } | null)
    | ({
        relationTo: 'knowledge-chunks';
        value: number | KnowledgeChunk;
      } | null)
    | ({
        relationTo: 'prompt-templates';
        value: number | PromptTemplate;
      } | null)
    | ({
        relationTo: 'lead-sources';
        value: number | LeadSource;
      } | null)
    | ({
        relationTo: 'leads';
        value: number | Lead;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  source?: T;
  isPublic?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        large?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "audit-logs_select".
 */
export interface AuditLogsSelect<T extends boolean = true> {
  action?: T;
  resource?: T;
  documentId?: T;
  actor?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  generateSlug?: T;
  slug?: T;
  summary?: T;
  body?: T;
  heroImage?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        keywords?: T;
        canonical?: T;
        ogImage?: T;
        noIndex?: T;
      };
  internalNotes?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "product-categories_select".
 */
export interface ProductCategoriesSelect<T extends boolean = true> {
  title?: T;
  generateSlug?: T;
  slug?: T;
  description?: T;
  sortOrder?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        keywords?: T;
        canonical?: T;
        ogImage?: T;
        noIndex?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products_select".
 */
export interface ProductsSelect<T extends boolean = true> {
  title?: T;
  generateSlug?: T;
  slug?: T;
  shortDescription?: T;
  description?: T;
  category?: T;
  coverImage?: T;
  gallery?: T;
  specifications?:
    | T
    | {
        label?: T;
        value?: T;
        id?: T;
      };
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        keywords?: T;
        canonical?: T;
        ogImage?: T;
        noIndex?: T;
      };
  internalNotes?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects_select".
 */
export interface ProjectsSelect<T extends boolean = true> {
  title?: T;
  generateSlug?: T;
  slug?: T;
  summary?: T;
  description?: T;
  location?: T;
  application?: T;
  coverImage?: T;
  gallery?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        keywords?: T;
        canonical?: T;
        ogImage?: T;
        noIndex?: T;
      };
  internalNotes?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  title?: T;
  generateSlug?: T;
  slug?: T;
  excerpt?: T;
  content?: T;
  category?: T;
  featuredImage?: T;
  publishedAt?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        keywords?: T;
        canonical?: T;
        ogImage?: T;
        noIndex?: T;
      };
  internalNotes?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "downloads_select".
 */
export interface DownloadsSelect<T extends boolean = true> {
  title?: T;
  generateSlug?: T;
  slug?: T;
  description?: T;
  type?: T;
  file?: T;
  coverImage?: T;
  isActive?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        keywords?: T;
        canonical?: T;
        ogImage?: T;
        noIndex?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "knowledge-documents_select".
 */
export interface KnowledgeDocumentsSelect<T extends boolean = true> {
  sourceTitle?: T;
  sourceType?: T;
  sourceURL?: T;
  sourceFile?: T;
  sourceVersion?: T;
  locale?: T;
  content?: T;
  reviewStatus?: T;
  reviewedAt?: T;
  reviewedBy?: T;
  indexStatus?: T;
  indexedAt?: T;
  embeddingModel?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "knowledge-chunks_select".
 */
export interface KnowledgeChunksSelect<T extends boolean = true> {
  document?: T;
  stableId?: T;
  index?: T;
  locale?: T;
  content?: T;
  sourceTitle?: T;
  sourceVersion?: T;
  sourceURL?: T;
  embeddingModel?: T;
  embeddingDimensions?: T;
  embeddedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "prompt-templates_select".
 */
export interface PromptTemplatesSelect<T extends boolean = true> {
  key?: T;
  purpose?: T;
  locale?: T;
  version?: T;
  template?: T;
  variables?: T;
  status?: T;
  model?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "lead-sources_select".
 */
export interface LeadSourcesSelect<T extends boolean = true> {
  name?: T;
  key?: T;
  channel?: T;
  isActive?: T;
  description?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "leads_select".
 */
export interface LeadsSelect<T extends boolean = true> {
  requestId?: T;
  idempotencyKey?: T;
  source?: T;
  locale?: T;
  status?: T;
  intentLevel?: T;
  assignedTo?: T;
  name?: T;
  company?: T;
  country?: T;
  email?: T;
  phone?: T;
  interest?: T;
  message?: T;
  sourceURL?: T;
  utm?:
    | T
    | {
        source?: T;
        medium?: T;
        campaign?: T;
        term?: T;
        content?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  siteName: string;
  siteDescription?: string | null;
  footerText?: string | null;
  logo?: (number | null) | Media;
  navigation?:
    | {
        label: string;
        page: number | Page;
        id?: string | null;
      }[]
    | null;
  contact?: {
    email?: string | null;
    phone?: string | null;
    whatsapp?: string | null;
    address?: string | null;
  };
  socialLinks?:
    | {
        platform: 'facebook' | 'instagram' | 'linkedin' | 'tiktok' | 'youtube' | 'other';
        url: string;
        id?: string | null;
      }[]
    | null;
  defaultSeo?: {
    title?: string | null;
    description?: string | null;
    /**
     * Comma-separated keywords for search and content planning.
     */
    keywords?: string | null;
    /**
     * Optional canonical URL for this locale.
     */
    canonical?: string | null;
    ogImage?: (number | null) | Media;
    noIndex?: boolean | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  siteName?: T;
  siteDescription?: T;
  footerText?: T;
  logo?: T;
  navigation?:
    | T
    | {
        label?: T;
        page?: T;
        id?: T;
      };
  contact?:
    | T
    | {
        email?: T;
        phone?: T;
        whatsapp?: T;
        address?: T;
      };
  socialLinks?:
    | T
    | {
        platform?: T;
        url?: T;
        id?: T;
      };
  defaultSeo?:
    | T
    | {
        title?: T;
        description?: T;
        keywords?: T;
        canonical?: T;
        ogImage?: T;
        noIndex?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}